/*                          ------ NOTE ------
 *  
 * None of this works, if I try to make it work again im going to fucking snap my laptop in half
 * If someone (or myself) ever figure this/build dependencies/gradle/maven/all this stupid bullshit,
 * this code (generated by ChatGPT so it won't even work anyways) is here to waste even more time,
 * on top of all the time that's been wasted trying to get it to run in the first place :)
 * 
 * If you care, this was written on May 16 2023
 * 
 */

// import org.apache.poi.ss.usermodel.*;
// import org.apache.poi.xssf.usermodel.XSSFWorkbook;
// import org.apache.poi.xssf.usermodel.XSSFSheet;
// import org.apache.poi.xssf.usermodel.XSSFRow;
// import org.apache.poi.xssf.usermodel.XSSFCell;


// import java.io.FileOutputStream;
// import java.io.IOException;

// public class ExcelManager {
//     public static void main(String[] args) {
//         Workbook workbook = new XSSFWorkbook();
//         Sheet sheet = workbook.createSheet("Sheet1");

//         Row headerRow = sheet.createRow(0);
//         Cell headerCell = headerRow.createCell(0);
//         headerCell.setCellValue("Hello");

//         try (FileOutputStream fileOut = new FileOutputStream("output.xlsx")) {
//             workbook.write(fileOut);
//             System.out.println("Excel spreadsheet created successfully.");
//         } catch (IOException e) {
//             e.printStackTrace();
//         }
//         workbook.close();
//     }
// }
